computer_assistant:
  base_topic: computer_assistant
  name: computer assistant
  unique_id: computer_assistant
  status_pub_interval: 2
  device:
    ids:
      - kasama_computer
    name: kasama_computer
    sw: 1.0.0
    mf: kasama
    cu: http://192.168.1.113
    model: kasama

switch:
  - name: computer on
    state_script: |
      test -f /tmp/computer
    on_script: |
      touch /tmp/computer
    off_script: |
      rm /tmp/computer
  - name: computer microphone
    on_script: |
      default_mic=$(pactl get-default-source)
      pactl set-source-mute ${default_mic} 0
    off_script: |
      default_mic=$(pactl get-default-source)
      pactl set-source-mute ${default_mic} 1
    state_script: |
      default_mic=$(pactl get-default-source)
      mic_muted=$(pactl get-source-mute "$default_mic" | awk '{print $2}')
      [ "$mic_muted" = "no" ]

number:
  - name: computer volume
    min: 0
    max: 100
    step: 5
    unit_of_measurement: "%"
    state_script: |
      default_sink=$(pactl get-default-sink)
      pactl get-sink-volume "$default_sink" | awk '{print $5}' | sed 's/%//'
    command_script: |
      default_sink=$(pactl get-default-sink)
      pactl set-sink-volume "$default_sink" "$1"%
